### ISSUE TITLE
service.start_launch doesnot address the rerun flag for the launches

### ISSUE THREAD

**Issue by ersuniljoshi** [reportportal/client-Python#108]
def start_launch(self,
                     name,
                     start_time,
                     description=None,
                     attributes=None,
                     mode=None,
                     **kwargs):

kwargs has never been used to add more data arguments.

        data = {
            "name": name,
            "description": description,
            "attributes": attributes,
            "startTime": start_time,
            "mode": mode,
            "rerun": ???  <-------
        }

**Comment by iivanou** [comment]
Already fixed.
