### ISSUE TITLE
Add a way to get launch UI id and UI URL.

### ISSUE THREAD

**Issue by NikitaFedoraev** [reportportal/client-Python#121]
`ReportPortalService()` does not have a method to get UI ID and URL that a user may use to get the launch in ReportPortal.like `http://172.17.120.254:8080/ui/#superadmin_personal/launches/all/11`

Would be great to have it. SO that we could print in in Pytest/other clients at the beginning/end of a session to be used by one click.

**Comment by HardNorth** [comment]
Done
