### ISSUE TITLE
client-Python seems have no way to use custom SSL certificates

### ISSUE THREAD

**Issue by ArchiDevil** [reportportal/client-Python#147]
Hi, we are trying to make it work with custom SSL certificates inside our corporate network. 

I haven't found any ways to make it use custom certificates because reportportal-client does not pass needed `requests` param to the user (`requests` library can accept a custom certificate file on connections). Do you have any plans to implement it or is there any other way to make it work?

**Comment by iivanou** [comment]
Hi, you can export the path to your self-signed certificate before running Python.

`export REQUESTS_CA_BUNDLE=/path/to/your/certificate.pem`?

**Comment by ArchiDevil** [comment]
For some reason, it does not work in a virtual environment, we are investigating and looking for other solutions if it does not work. Is it possible to propose a PR here, or you don't accept PRs from outer sources?

**Comment by iivanou** [comment]
All PRs are appreciated.

**Comment by ArchiDevil** [comment]
Thanks for the response. I will think about making a PR.
