### ISSUE TITLE
Add support to push tags in ReportPortalService class for Report Portal Version 5

### ISSUE THREAD

**Issue by vipin3699** [reportportal/client-Python#161]
Hi all, in client-Python v3 we can pass tags in [start_launch](https://github.com/reportportal/client-Python/blob/v3/reportportal_client/service_async.py#L250) method of class ReportPortalServiceAsync but this feature seems to be missing in 
client-Python v5 with class ReportPortalService.

Can we implement the same in ReportPortalService or in client-python v5?
I will try to implement it if I can by the time creating this Feature request so that if anyone else has the feature implementd they can push there changes. :)

**Comment by iivanou** [comment]
tags have been renamed to [attributes](https://github.com/reportportal/client-Python/blob/master/reportportal_client/service.py#L219) in V5.

**Comment by vipin3699** [comment]
Acknowledge I will put it in the README.md
We can close the issue now Thanks :)
