### ISSUE TITLE
Test hangs if the launch request gets no response

### ISSUE THREAD

**Issue by lorjala** [reportportal/client-Python#170]
**Describe the bug**
Test hangs on ReportPortalService.start_launch() if report portal service is accessible but cannot handle launch POST request. https://github.com/reportportal/client-Python/blob/0bf36d7f8aecec126c1adae9641ae59c77e3bb53/reportportal_client/service.py#L231 never timeouts in that instance.

This issue is caused by no response from the service-api but the client should handle even that case.

**Steps to Reproduce**
1. Deploy [report portal stack](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml).
2. Fill the disk where the stack is running.
2. Start test from different machine with the rp_endpoint set.

**Expected behavior**
service-api sends a fail/success response normally or the python client timeouts if no response.

**Actual behavior**
Test hangs on the launch POST request.

**Package versions**
pytest-reportportal==5.0.11
reportportal-client==5.1.0

**Additional context**
Related service-api issue: https://github.com/reportportal/service-api/issues/1546

**Comment by HardNorth** [comment]
Well, OKay, we need a fix.
