### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'log'

### ISSUE THREAD

**Issue by wtrwinberg** [reportportal/client-Python#182]
A PytestUnhandledThreadExceptionWarning is triggered when returning the log property from the rp_client object:

`AttributeError: 'NoneType' object has no attribute 'log'`

This warning does not appear with reportportal-client at version `5.1.0` and below but appears at `5.2.0` onwards.

**Comment by HardNorth** [comment]
@wtrwinberg I don't see such error on our [examples](https://github.com/reportportal/examples-python/tree/master/pytest). Which agent version do you use?

**Comment by wtrwinberg** [comment]
@HardNorth The agent version is the latest available: 5.1.1

**Comment by HardNorth** [comment]
@wtrwinberg I'm still not getting it. Where do you get `rp_client` object? How do you get `log` property? Could you please point on some code?

**Comment by HardNorth** [comment]
Actually there is no `log` property in `RPClient` class. There is `log` method, but it does not return anything by design.

**Comment by wtrwinberg** [comment]
That's correct - the log method is utilised by default, where the warning appears when it emits rp_client.log at the return statement in the following file [https://github.com/reportportal/client-Python/blob/develop/reportportal_client/logs/__init__.py](https://github.com/reportportal/client-Python/blob/develop/reportportal_client/logs/__init__.py)

**Comment by HardNorth** [comment]
Ahh, thanks, now I got it.

**Comment by HardNorth** [comment]
https://github.com/reportportal/client-Python/releases/tag/5.2.2
