### ISSUE TITLE
Launch is not populated on the gui but a uuid for that launch is generated

### ISSUE THREAD

**Issue by rujutashinde** [reportportal/client-Python#190]
Hello

We use reportportal_client in our tool to import xunit files to RP instance.Once launch is completed we use the below  api  to get the launch id 
`/launch?filter.eq.uuid=<UUID>`

We are seeing this  issue where the launch starts and finishes and generates the uuid, but while using the above api , the response is empty.  The gui also does not show any launch started.  This issue is seen around every 10 launches

output from the uuid filter api 
```

DEBUG (api_get) url: https://<OUR_RP_INSTANCE>/api/v1/<OUR_PROJECT>/launch?filter.eq.uuid=b399ce6a-446b-4843-a8e2-56d44514b306
2022-07-08 10:57:33,627 DEBUG (api_get) r.status_code: 200
2022-07-08 10:57:33,628 DEBUG (api_get) r.text: {"content":[],"page":{"number":1,"size":20,"totalElements":0,"totalPages":0}}

```
If i use this uuid and run it from the swagger api provided  on the RP instance, i still get an empty content with 200 response.

Any idea where i can debug further or what could be the reason of this behavior

```
reportportal-client==5.2.2
Python 3.9.9
ReportPortal Current version:API Service: 5.6.3;Authorization Service: 5.6.3;Service UI: 5.6.0;

```
Appreciate any help!
Thanks,
Rujuta

**Comment by rujutashinde** [comment]
Hello, I was hoping someone can help us out with the issue, we see this more often and it is reproducible on a couple of our RP instances. We see that launch id comes back null in 2 different cases:

1. the launch is successful and seen on the RP instance. here if we retrieve the launch `id` using the launch `uuid` after some time(say 5-10 sec) we get back the launch `id`
2. the launch looks like it is successful but is not and  it is not even seen on the RP instance. here the  if we retrieve the launch `id` using the launch `uuid` after some time(say 5-10 sec) we get back empty content of the response.

How we are using the reportportal_client service in our tool:

1. create service
```             self._service = ReportPortalService(endpoint=self.endpoint,
                                                project=self.project,
                                                token=self.api_token,
                                                log_batch_size=1)
            self._service.session.verify = False
```
2. use service.start for the launch, get back a uuid for the launch
```             self._launch_uuid = \
                self._service.start_launch(name=self.name,
                                           start_time=self.start_time,
                                           attributes=self.attributes,
                                           description=self.description)
            g.log.debug('Started launch with uuid %s ', self._launch_uuid)
 ```
3. use service.start and finish for test case, test case class and test suite, get individual uuid for each of these items
```             self.item_id = self.service.start_test_item(
                name=self.name,
                start_time=str(int(time.time() * 1000)),
                item_type=self.item_type,
                attributes=self.ts_properties,
                parent_item_id=self.parent_id
            )
```
```
  ret_msg = self.service.finish_test_item(self.item_id, end_time=str(int(time.time() * 1000)),
                                          status=self.status)
```
5. use service.finish for the launch
 ``` ret_message = self._service.finish_launch(end_time=self.end_time) ```
6. retrieve the launch id using the Reportportal api `/launch?filter.eq.uuid=<UUID>`
7. terminate the service
``` self._service.terminate() ```

Is there a way to catch additional errors if they are taking place during the starting of any launch or test items OR a way to debug why a certain launch is not seen on the RP instance when an uuid is generated?

**Comment by rujutashinde** [comment]
Hello @HardNorth Can someone from the project team provide some information on this issue?  we are seeing a lot of issues where after the service starts the launch , the launch id returned is None.  This causing a lot of failures for our project . Any help would be appreciated

**Comment by HardNorth** [comment]
@rujutashinde I don't see your code to say anything and I don't want to guess. I can only say, that our integrations works well.

**Comment by rujutashinde** [comment]
Thanks @HardNorth ,  is there a suggested guide as to what should be the rabbitMQ  configurations?

**Comment by HardNorth** [comment]
@rujutashinde No, we don't have any documents for RabbitMQ tuning. But I would suggest to investigate the root cause of disappearing launch uuids:
* Does it happen during high-load times?
* Is it just delay, or launches will be never created?
* If it's not created what is the reason, what server logs say?
* etc.

**Comment by rujutashinde** [comment]
> @rujutashinde No, we don't have any documents for RabbitMQ tuning. But I would suggest to investigate the root cause of disappearing launch uuids:
> 
> * Does it happen during high-load times?
> * Is it just delay, or launches will be never created?
> * If it's not created what is the reason, what server logs say?
> * etc.

Appreciate the feedback!  so we have multiple instances of ReportPortal, and they have heavy-load most times, so i am seeing both issues launches never get created and sometimes there is a delay in launch creation. we are trying to figure out to get more info from the rabbit mq logs

**Comment by rujutashinde** [comment]
Hello @HardNorth  related question, we use the service.py to start/finish launch and test items.
To assist with the issues that occur on the RP instance which can cause delay or loss from the rabbit mq pods, we wanted to add some error handling on our tool, where we can catch the errors the python-reportportal client sees when starting/finishing the launch.
 From this lines of code https://github.com/reportportal/client-Python/blob/develop/reportportal_client/service.py#L253-L259,
```
        try:
            r = self.session.post(url, json=data, verify=self.verify_ssl,
                                  timeout=self.http_timeout)
        except (ValueError, KeyError, IOError) as exc:
            logger.warning("Report Portal Start Launch request failed",
                           exc_info=exc)
            return
```
 when an error is seen by the service.py it just `returns ` and does not raise the error, hence our tool can never quite get what could be the actual error from the reportportal python client side. I looked at the `client.py `  here too the errors are not reported back 

**Is there a way we can catch these errors ??** OR **can it be added to return the errors?**

For e.g. when i do not have SSL certificates enabled in my environment and i do a start launch as below,
```
            self._service = ReportPortalService(endpoint=self.endpoint,
                                                project=self.project,
                                                token=self.api_token,
                                                log_batch_size=1)


        try:
            self._launch_uuid = \
                self._service.start_launch(name=self.name,
                                           start_time=self.start_time,
                                           attributes=self.attributes,
                                           description=self.description,
                                           )

            if self._launch_uuid is not None:
                g.log.debug('Started launch with uuid %s ', self._launch_uuid)
                return self._launch_uuid
            else:
                raise ReportPortalClassError(
                    "After the wait the launch uuid was still returned as  %s" % (self._launch_uuid))
               )
        except (Exception, HTTPError) as e:
            raise e
```
 i cannot get the actual failure that takes place on the ReportPortalService. If i have to debug , i see that the launch fails due to error `` requests.exceptions.SSLError: HTTPSConnectionPool(host='reportportal-<our project name>.com', port=443): Max retries exceeded with url: /api/v2/rpprepoc_debug/launch (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))`` but this error is never reported back

TIA
Rujuta

**Comment by HardNorth** [comment]
@rujutashinde We are not throwing back errors because we are reporting tool and it's logically incorrect if a reporting tool break test run. As for your case I believe it's more that enough information to solve the case. `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate` means that either you run your test on a system where no CA Certificate installed, or you use self-signed certificates. Both problems has nothing to do with Report Portal itself, it's you area of responsibility how you configure SSL in your system. We provide `verify_ssl` parameter which anyone can use to configure SSL on client side, as per requests documentation:
https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification

https://github.com/reportportal/client-Python/blob/develop/reportportal_client/service.py#L184
https://github.com/reportportal/client-Python/blob/develop/reportportal_client/client.py#L55

**Comment by rujutashinde** [comment]
@HardNorth Thank you!
