### ISSUE TITLE
get_launch_ui_url returns incorrect url in some cases

### ISSUE THREAD

**Issue by dagansandler** [reportportal/client-Python#192]
**Describe the bug**

The returned URL is sometimes incorrect, and while it leads to the correct launch, navigation is broken. 
This is somewhat a bug in RP UI, but can easily be averted when building the URL.

1. When running in `mode="DEBUG"` the launch url should be `https://rp.company.com/ui/#project/userdebug/all/73327` but is instead returned as `https://rp.company.com/ui/#project/launches/all/73327`

2. If the project name was set using upper case letters the returned url is `https://rp.company.com/ui/#PROJECT/launches/all/73327` but this seems to break navigation as the project name should be lowercased.

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/client-Python/releases/tag/5.2.4
