### ISSUE TITLE
`max_pool_size` not worked without `retries` setting

### ISSUE THREAD

**Issue by ericscobell** [reportportal/client-Python#200]
**Describe the bug**
I am encountering an issue where `HTTPAdapter.pool_maxsize` seems to be limited to `10` even when using the newest version of `ReportPortal`. The expected behaviour is for `HTTPAdapter.pool_maxsize` to be set to the default value `50`, as specified in ReportPortalClient construction.

https://github.com/reportportal/client-Python/blob/8041c64a24925d648b25d449489bb3a15cd3c727/reportportal_client/service.py#L186

**Steps to Reproduce**
When starting any test cases with `ReportPortalClient v5.2.5`, I noticed that the `HTTPAdapter.pool_maxsize` did not change.

**Expected behavior**
The `HTTPAdapter.pool_maxsize` should be `50`, which is the default value for ReportPortalClient construction.

**Actual behavior**
Looking through the code, I discovered that `HTTPAdapter.pool_maxsize` seems to be capped at `10`. Here's where it occurs: https://github.com/reportportal/client-Python/blob/8041c64a24925d648b25d449489bb3a15cd3c727/reportportal_client/service.py#L217

I want to clarify if there are any concerns about this usage. Is it possible to increase the size of `max_pool_size` without setting `retries`?

Thank you, and I look forward to your reply.

**Package versions**
`reportportal-client: 5.2.5`

**Comment by HardNorth** [comment]
@zhangzheng1214 service.py is deprecated and doesn't mean to be updated: https://github.com/reportportal/client-Python/blob/develop/reportportal_client/service.py#L3

If you update client.py, then I can approve the fix, but I don't want to touch service.py in any case.

**Comment by zhangzheng1214** [comment]
@HardNorth Thank you for your response. I have reverted the changes made in `service.py` and added some code to `client.py`. Could you please review it when you have a chance?
