### ISSUE TITLE
There's no `reportportal_client.ReportPortalService` class anymore, contrary to what the README indicates

### ISSUE THREAD

**Issue by Victoremepunto** [reportportal/client-Python#205]
**Describe the bug**
Unable to follow the README example for creating a new ReportPortal client using this library.

**Steps to Reproduce**
* install latest version of library:

``` 
pip install reportportal-client
```

* Test on Python shell
```
# python

from reportportal_client import ReportPortalService
```

**Expected behavior**

Import works successfully

**Actual behavior**

Error on importing

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ReportPortalService' from 'reportportal_client' (/home/foo/.venv/lib64/python3.11/site-packages/reportportal_client/__init__.py)
```

**Package versions**
Include version info of the following packages: reportportal-client

```
pip list installed | grep -i report
reportportal-client 5.3.0
```

**Additional context**

**Comment by HardNorth** [comment]
@Victoremepunto README.md is updated, thank you!
