### ISSUE TITLE
HTTP client retries feature

### ISSUE THREAD

**Issue by fslevoaca-ionos** [reportportal/client-Python#232]
Hi, 

I have ReportPortal dahsboard and client-Python running in different environments. The network between these environments is sometimes unstable and the connection between client-Python and ReportPortal sometimes drops.
Is it possible to enable a retry mechanism such that if client connection fails it should retry it ?

**Comment by HardNorth** [comment]
@fslevoaca-ionos It's already implemented, please check our documentation.

- Pytest: https://reportportal.io/docs/log-data-in-reportportal/test-framework-integration/Python/pytest/#configuration
- Robot Framework: default value of 5 retries applied.

**Comment by fslevoaca-ionos** [comment]
Ah, I see.  I've missed this configuration from the documentation.
Thanks !
