### ISSUE TITLE
Launch does not finish when running client with launch_uuid

### ISSUE THREAD

**Issue by roeycarmi** [reportportal/client-Python#243]
**Describe the bug**
I want to separate my launch over a 2 python script. 
First script starts a launch and fill it with some test cycles, and then pass the launch uuid to the second script.
The second script creates the RPClient object with the parameter launch_uuid=<given uuid>, add some test cycles and finishes the launch.

This does not seem to be working...

**Steps to Reproduce**
1. First script:
rp_client = RPClient(
    endpoint=RP_URL,
    project=RP_PROJECT,
    api_key=API_KEY
)
rp_client.start_launch(
    name='Test Launch',
    start_time=timestamp(),
    description='Testing...',
)
\<adding tests\>
\<returns launch uuid\>

2. Second script:
rp_client = RPClient(
    endpoint=RP_URL,
    project=RP_PROJECT,
    api_key=API_KEY,
    launch_uuid=\<given launch uuid\>
)
\<adding some tests\>
rp_client.finish_launch(end_time=timestamp())

**Expected behavior**
For script one to start a launch and add some tests, and for the second script to "continue" that launch, add some tests and close the launch.

**Actual behavior**
Tests from both scripts are successfully added to the launch, but the launch does not finish - it is stuck on "in progress".

**Package versions**
reportportal-client version 5.5.9

**Additional context**
Report Portal version 5.12.0
The report portal instance is ran using docker-compose

**Comment by HardNorth** [comment]
Duplicates #242

**Comment by roeycarmi** [comment]
I read #242 and sorry but I don't quite understand the 'design'. You say to use the api, and that the python client should close a launch it started. But i don't get it... What is the point of python package if i need to use api?
My situation is that i have a few jenkins stages, each should run bazel, then parse and push its test.xml to reportportal. Why can't I start a launch in the first jenkins stage and close it at the last one?
Thanks in advance for your response and hard work!
