### ISSUE TITLE
run pybot got the 'NoneType' object has no attribute 'put_nowait' errors

### ISSUE THREAD

**Issue by koala2012** [reportportal/client-Python#27]
I just run the pybot command, but an got error as below

pybot --listener robotframework_reportportal.listener --variable RP_UUID:"b514a045-0a6d-4dc9-a496-fae494f8c928" --variable RP_ENDPOINT:"http://ip172-18-0-10-bc51moquguig00f5g7i0-8080.direct.labs.play-with-docker.com" --variable RP_LAUNCH:"Robotframework_test_demo" --variable RP_PROJECT:"Robotframework_test_demo" -d Results test.robot

==============================================================================
Test
==============================================================================
test                                                                  | PASS |
------------------------------------------------------------------------------
[ ERROR ] Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
gfp                                                                   Traceback (most recent call last):
  File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service_async.py", line 204, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service.py", line 187, in finish_test_item
    return _get_msg(r)
  File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service.py", line 22, in _get_msg
    return _get_data(response)["msg"]
  File "/Users/Larry/anaconda2/lib/python2.7/site-packages/reportportal_client/service.py", line 34, in _get_data
    raise ResponseError(error_messages[0])
ResponseError: 5000: Unclassified error [null]
[ ERROR ] Calling method 'end_keyword' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
[ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
[ ERROR ] Calling method 'end_keyword' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'
[ ERROR ] Calling method 'end_test' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'put_nowait'

my robot framework version is Robot Framework 3.0.2 (Python 2.7.12 on darwin)

**Comment by evjlobanova** [comment]
@krasoffski Yury, maybe you can also help with this and this issue https://github.com/reportportal/client-Python/issues/27 ?

**Comment by krasoffski** [comment]
Unfortunately I am short of time now and will not have free time slots in the nearest future.

**Comment by koala2012** [comment]
@ailjushkin I just hade a try, but also get the error came out, could you help to see if my command has wrong?

pybot --listener reportportal_listener --escape quot:Q \
> --variable RP_ENDPOINT:http://ip172-18-0-30-bch7aru08n7000avd9d0-8080.direct.labs.play-with-docker.com \
> --variable RP_UUID:9c6f96c1-059b-47f7-85bc-c09da79d38e4 \
> --variable RP_LAUNCH:"Demo Tests" \
> --variable RP_PROJECT:DEMO_USER_PERSONAL test.robot
==============================================================================
Test
==============================================================================
[ ERROR ] Calling method 'end_test' of listener 'reportportal_listener' failed: ResponseError: 5000: Unclassified error [null]
test                                                                  | PASS |
------------------------------------------------------------------------------
[ ERROR ] Calling method 'end_test' of listener 'reportportal_listener' failed: ResponseError: 5000: Unclassified error [null]
gfp                                                                   | PASS |
------------------------------------------------------------------------------
[ ERROR ] Calling method 'end_suite' of listener 'reportportal_listener' failed: ResponseError: 40022: Finish test item is not allowed. Test item '5b2278611aa8410001bbbba2' has descendants with 'IN_PROGRESS' status. All descendants '[test, gfp]'
Test                                                                  | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed

**Comment by arozumenko** [comment]
@koala2012 
checked on robotframework-3.0.2 and robotframework-3.0.4
with reportportal_client-3.2.0 and robotframework-reportportal-3.0.0
was not able to reproduce. 

Could you please verify?

**Comment by arozumenko** [comment]
Verified on robotframework-reportportal==2.5.4 and reportportal-client==2.6.0 also file

**Comment by moijes12** [comment]
I am seeing this same error. Which is the latest reportportal-client that I may use ? Note that I am using report portal build 4.2.2

**Comment by arozumenko** [comment]
No response, closed as obsolete
