### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by s0undt3ch** [reportportal/client-Python#28]
Can you please release the current code which has `parameters` support?

**Comment by DzmitryHumianiuk** [comment]
@krasoffski @frizzby

**Comment by osherdp** [comment]
Any progress with it?
BTW, you can make releasing versions to PyPI much easier and automated by using [travis](https://github.com/gregoil/ipdbugger/blob/master/.travis.yml).

**Comment by DzmitryHumianiuk** [comment]
@osherdp still not released?

**Comment by osherdp** [comment]
No, still no version

**Comment by DzmitryHumianiuk** [comment]
@krasoffski can we automate it with Travis CI, not to disturb you every time?

**Comment by DzmitryHumianiuk** [comment]
@reportportal/python-contributors Ch-t could you plz take a look?

**Comment by osherdp** [comment]
@DzmitryHumianiuk / @krasoffski see #30
