### ISSUE TITLE
Binary data upload handles are not properly implemented

### ISSUE THREAD

**Issue by krasoffski** [reportportal/client-Python#4]
Hi,
I tried to upload binary data to Report Portal but faced with issues that python client does not provide method to perform this.

As I understood we need to implement approach like this: https://github.com/reportportal/client-javascript/blob/master/lib/client.js#L89.

__Need to implement FileRQ here with appropriate multi-part post request and service handler like `send_file`.__

**Comment by krasoffski** [comment]
Have to pass file like object to log. Closed.

**Comment by PositiveAlex** [comment]
Thanks for the issue. Will try to implement this.

**Comment by krasoffski** [comment]
@avarabyeu 
I tried to add simple file uploaded to `client-python`  without any checks which looks like this (based on `client-js`):
```
def send_file(self, save_log_rq, path):
    url = self.uri_join(self.base_url, "log")
    basename = os.path.basename(path)
    files = {
        'json_request_part': (None, save_log_rq.data, 'application/json'),
        'file': (basename, open(path, 'rb'), 'application/octet-stream'),
    }
    headers = {"Authorization": "{0} {1}".format("bearer", self.token)}

    r = self.session.post(url=url, headers=headers, files=files)
    return EntryCreatedRS(raw=r.text)
```
As a result python `requests` lib creates following post request with no log message/attachment created in the Report Portal:
![image](https://cloud.githubusercontent.com/assets/1073415/25912672/c9b8054e-35c0-11e7-9708-7dc4b3001713.png)
 __It would be very helpful if core team shows correct message (post multi-form) format for creating log message with attachment.__

**Comment by krasoffski** [comment]
Added simple `attach` method for now (most probably batch pushes will require logs reworking).
Closed.
