### ISSUE TITLE
https connection issue with report portal python requests

### ISSUE THREAD

**Issue by sumeetm18** [reportportal/client-Python#48]
Hi Team,

Could you please help me with this issue. We are not able to send the data to report portal using python client with https connection.

Error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/reportportal_client/service_async.py", line 208, in process_item
    getattr(self.rp_client, method)(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/reportportal_client/service.py", line 144, in finish_launch
    status=status)
  File "/usr/local/lib/python2.7/site-packages/reportportal_client/service.py", line 137, in _finalize_launch
    r = self.session.put(url=url, json=data)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='report-portal.****.com', port=8080): Max retries exceeded with url: /api/v1/api_automation/launch/None/finish (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

Could you please check and help here.

**Comment by ndelon** [comment]
Hello,

I guess that this question as something to do with this other question: https://groups.google.com/d/msg/lemoncheesecake/InueB6j7-jY/HA4Cive7AQAJ ;-)

As indicated in the post I'm referring to, you can use the REQUEST_CA_BUNDLE environment variable to point a trusted certificate chain (your ReportPortal self-signed certificate for instance).

For a more general perspective, the ReportPortal python client ReportPortalService and ReportPortalServiceAsync classes provide a verify_ssl argument https://github.com/reportportal/client-Python/blob/master/reportportal_client/service_async.py#L149 which is said to "not verify ssl certificates". Setting this parameter to False should therefore disable peer certificate checking. Behind the scene the parameter value is directly used to assign the "verify" argument of requests (see https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification). It means that you could use this value not only to disable peer certificate checking, but also set to whatever kind of value requests is supporting (a certificate chain file for instance).
However, this behavior is not explicitly documented by the ReportPortal python client. Maybe the python client documentation could be improved to explicitly say so. What is the ReportPortal python client Team's opinion on this ?

**Comment by DzmitryHumianiuk** [comment]
@sumeetm18 did you resolve it?

**Comment by sumeetm18** [comment]
Yes
