### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by wahahaXDD** [reportportal/client-Python#50]
For what I've seen, the released code on pypi seems to be outdated.
The support for verify ssl and get project settings is not available with current version(3.2.0).
Is the current code ready to release?
What's the process to get it release?

**Comment by zeburek** [comment]
@DzmitryHumianiuk @krasoffski 
Guys, could you please upload latest packages on PyPi?
Actually it breaks the functionality of agent-pytest

**Comment by DzmitryHumianiuk** [comment]
@krasoffski that should be yours. we don't have release job for `client-python` in our jenkins

**Comment by Almost1990** [comment]
3.2.3 release should solve the issue.

**Comment by DzmitryHumianiuk** [comment]
https://pypi.org/project/reportportal-client/3.2.3/
