### ISSUE TITLE
Pass specific launch_id in start_test_item 

### ISSUE THREAD

**Issue by kdivekar** [reportportal/client-Python#51]
I am integrating reportportal with my automation framework. The way the framework is designed, it creates the launch in the initiation but I need to call start_test_items from individual test case (python classes) files. For which the solution I thought is to pass launch_id in start_test_item().

I made the required changes in start_test_item and it works fine for me now. 
If  this sounds to be a generic requirement, I can send a PR on service.py

**Comment by sounak95** [comment]
Could you please provide me the code for the same? It would act as a good reference for my test framework integration.

**Comment by DzmitryHumianiuk** [comment]
@kdivekar you can create an example, and send it as a pull request into this repo.
so the rest of users can take a look.
and team can decide it worth to be included in core
