### ISSUE TITLE
How to send screenshot to report portal

### ISSUE THREAD

**Issue by Dhams-1** [reportportal/client-Python#68]
Hi All,

I am very new to reportportal. I have installed agent for robotframework. I would like to send the failure cases screenshots to report portal i went through the code from here https://github.com/reportportal/client-Python#send-attachement-screenshots

but I am not able to follow it on where to add this code snippet. Kindly help me with the same.

Case 1 - pass file-like object
with open(screenshot_file_path, "rb") as image_file:
    rp_logger.info("Some Text Here",
                            attachment={"name": "test_name_screenshot.png",
                                                 "data": image_file,
                                                 "mime": "image/png"})
Case 2 - pass file content itself (like you did)
with open(screenshot_file_path, "rb") as image_file:
        file_data = image_file.read()

rp_logger.info("Some Text Here",
                       attachment={"name": "test_name_screenshot.png",
                                             "data": file_data,
                                             "mime": "image/png"})

**Comment by nepatriots21** [comment]
Did you figure it out @Dhams-1 ??
