### ISSUE TITLE
item_type= step is being logged as a Test method in rp portal

### ISSUE THREAD

**Issue by 2vireddy** [reportportal/client-Python#79]
I have the below code to log a test
  
![TEST_REQUEST](https://user-images.githubusercontent.com/29040810/77259526-0278d400-6ca8-11ea-8ef1-231fe1b481f0.png)

and below code to log steps to the test

    
![STEP_REQUEST](https://user-images.githubusercontent.com/29040810/77259592-8763ed80-6ca8-11ea-953d-13d30adeabb5.png)

But the RP shows STEP log request as TEST 
![image](https://user-images.githubusercontent.com/29040810/77259033-a82a4400-6ca4-11ea-8e19-e7c42ca855e1.png)

Please let me know if this is an issue or wrong implementation

**Comment by 2vireddy** [comment]
passed has_stats = False in the above request and it is reported as a step, however the description is not populated if has_stats = False

**Comment by iivanou** [comment]
That's correct, you should add the kay pair of has_stats=False to your request indicating RP that you are reporting a test step.
