### ISSUE TITLE
incorrect processor info in docker container

### ISSUE THREAD

**Issue by UncleTom** [reportportal/client-Python#86]
platform.processor() is not work in docker container. the value is empty, and cannot post to API.

```python
# tmp fix
        return {'agent': agent,
                'os': platform.system(),
                'cpu': platform.processor(),
                'machine': platform.machine()}
```
tmp fix
```python
        return {'agent': agent,
                'os': platform.system(),
                'cpu': (platform.processor() if platform.processor() else 'unkown'),
                'machine': platform.machine()}
```

**Comment by iivanou** [comment]
According to the documentation:

> platform.processor()
> Returns the (real) processor name, e.g. 'amdk6'.
> 
> An empty string is returned if the value cannot be determined. 

https://docs.python.org/3/library/platform.html

**Comment by UncleTom** [comment]
Yes, but API does not allow empty value.

**Comment by dkuchynskyi** [comment]
Hi! 
Could you please give any updates about it?
